# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shopping' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  inhibit_all_warnings!

  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'AFNetworking'
  pod 'MJRefresh’
  pod 'SDWebImage', '~> 4.0'
  pod 'SDCycleScrollView','~> 1.75'
  
  # Pods for Shopping

end
